136: warning: in "test_BOOST_WARN": condition sizeof(int) == sizeof(short) is not satisfied
139: info: check sizeof(unsigned char) == sizeof(char) passed
161: error: in "test_BOOST_CHECK": check false failed
162: error: in "test_BOOST_CHECK": check 1==2 failed
163: error: in "test_BOOST_CHECK": check i==1 failed
166: info: check i==2 passed
173: error: in "test_BOOST_REQUIRE": not aborted
175: fatal error: in "test_BOOST_REQUIRE": critical check false failed
179: fatal error: in "test_BOOST_REQUIRE": critical check j > 5 failed
182: info: check j < 5 passed
182: error: in "test_BOOST_REQUIRE": not aborted
196: info: check 'object size 33 is too small' passed
213: error: in "test_BOOST_CHECK_MESSAGE": Well, may be that what I believe in
215: error: in "test_BOOST_CHECK_MESSAGE": Checking predicate failed. Some explanation
218: info: check 'Could it fail?' passed
223: error: in "test_BOOST_CHECK_MESSAGE": Comparing 1 and 2: some explanation
230: fatal error: in "test_BOOST_REQUIRE_MESSAGE": Here we should stop
233: info: check 'That's OK' passed
233: error: in "test_BOOST_REQUIRE_MESSAGE": not aborted
240: error: in "test_BOOST_ERROR": Fail to miss an error
247: fatal error: in "test_BOOST_FAIL": No! No! Show must go on.
263: error: in "test_BOOST_CHECK_THROW": exception my_exception is expected
266: warning: in "test_BOOST_CHECK_THROW": exception my_exception is expected
269: fatal error: in "test_BOOST_CHECK_THROW": exception my_exception is expected
275: info: check 'exception my_exception is caught' passed
282: error: in "test_BOOST_CHECK_EXCEPTION": incorrect exception my_exception is caught
285: info: check 'incorrect exception my_exception is caught' passed
297: error: in "test_BOOST_CHECK_NO_THROW": exception thrown by throw my_exception()
343: error: in "test_BOOST_CHECK_EQUAL": check i == j failed [1 != 2]
349: error: in "test_BOOST_CHECK_EQUAL": check str1 == str2 failed [test1 != test12]
352: error: in "test_BOOST_CHECK_EQUAL": check i+1 == j failed [4 != 2]
355: info: check str1 == str3+1 passed
364: fatal error: in "test_BOOST_CHECK_EQUAL": critical check str1 == str2 failed [test != null string]
370: warning: in "test_BOOST_CHECK_EQUAL": condition b1 == b2 is not satisfied [B(1) != B(2)]
376: error: in "test_BOOST_CHECK_EQUAL": check c1 == c3 failed [C(0,100) != C(1,102)]. Index mismatch
377: error: in "test_BOOST_CHECK_EQUAL": check c1 == c2 failed [C(0,100) != C(0,101)]. Id mismatch
381: error: in "test_BOOST_CHECK_EQUAL": check ch1 == ch2 failed [0xfffffffe != 0xfffffffd]
392: error: in "test_BOOST_CHECK_LOGICAL_EXPR": check ++i != j failed [2 == 2]
394: error: in "test_BOOST_CHECK_LOGICAL_EXPR": check i < j failed [2 >= 2]
395: error: in "test_BOOST_CHECK_LOGICAL_EXPR": check i > j failed [2 <= 2]
402: error: in "test_BOOST_CHECK_LOGICAL_EXPR": check i <= j failed [3 > 2]
403: error: in "test_BOOST_CHECK_LOGICAL_EXPR": check j >= i failed [2 < 3]
408: error: in "test_BOOST_CHECK_LOGICAL_EXPR": check str1 != str2 failed [test1 == test1]
438: error: in "test_BOOST_CHECK_PREDICATE": check is_even( i ) failed for ( 17 )
441: error: in "test_BOOST_CHECK_PREDICATE": check not_equal_to<int>()( i, 17 ) failed for ( 17, 17 )
447: warning: in "test_BOOST_CHECK_PREDICATE": condition moo( 12, i, j ) is not satisfied for ( 12, 17, 15 )
455: error: in "test_BOOST_CHECK_PREDICATE": check compare_lists( l1, l2 ) failed for ( ,  ). Different sizes [2!=0]
466: error: in "test_BOOST_REQUIRE_PREDICATE": not aborted
468: fatal error: in "test_BOOST_REQUIRE_PREDICATE": critical check less_equal<int>()( arg2, arg1 ) failed for ( 2, 1 )
489: error: in "test_BOOST_CHECK_EQUAL_COLLECTIONS": check { testlist.begin(), testlist.end() } == { pattern, pattern+7 } failed. 
Mismatch in a position 2: 4 != 3
Mismatch in a position 5: 7 != 6
490: error: in "test_BOOST_CHECK_EQUAL_COLLECTIONS": check { testlist.begin(), testlist.end() } == { pattern, pattern+2 } failed. 
Collections size mismatch: 7 != 2
499: error: in "test_BOOST_CHECK_BITWISE_EQUAL": check (char)0x06 =.= (char)0x16 failed. 
Mismatch in a position 4
502: warning: in "test_BOOST_CHECK_BITWISE_EQUAL": condition (char)0x26 =.= (char)0x04 is not satisfied. 
Mismatch in a position 1
Mismatch in a position 5
505: fatal error: in "test_BOOST_CHECK_BITWISE_EQUAL": critical check (char)0x26 =.= (int)0x26 failed. 
Operands bit sizes mismatch: 8 != 32
still testing
1+1=2
2+2=4
struct A
0x14
  20
0: fatal error in "test_BOOST_TEST_CHECKPOINT": C string: some error
540: last checkpoint: Going to do a silly things
0: fatal error in "test_BOOST_TEST_PASSPOINT": unknown type
551: last checkpoint
608: error: in "test_context_logging": check false failed
Failure occurred in a following context:
    some context
612: error: in "test_context_logging": check false failed
Failure occurred in a following context:
    some more context: 12
617: error: in "test_context_logging": check false failed
Failure occurred in a following context:
    info 1
    info 2
    info 3
620: error: in "test_context_logging": check false failed
Failure occurred in a following context:
    some sticky context
623: error: in "test_context_logging": check false failed
Failure occurred in a following context:
    some sticky context
    more context
626: error: in "test_context_logging": check false failed
Failure occurred in a following context:
    some sticky context
    different subcontext
630: error: in "test_context_logging": check false failed
Failure occurred in a following context:
    outer context
633: error: in "test_context_logging": check false failed
Failure occurred in a following context:
    outer context
    inner context
636: error: in "test_context_logging": check false failed
Failure occurred in a following context:
    outer context
653: info: check true passed
654: error: in "test_BOOST_TEST_universal": check false failed
657: info: check bc passed
660: error: in "test_BOOST_TEST_universal": check i == 2 failed [1!=2]
661: error: in "test_BOOST_TEST_universal": check i != 1 failed [1==1]
662: error: in "test_BOOST_TEST_universal": check i > 2 failed [1<=2]
663: error: in "test_BOOST_TEST_universal": check i < 1 failed [1>=1]
664: error: in "test_BOOST_TEST_universal": check i <= 0 failed [1>0]
665: error: in "test_BOOST_TEST_universal": check i >= 5 failed [1<5]
669: error: in "test_BOOST_TEST_universal": check i+j >= 5 failed [1+2<5]
670: error: in "test_BOOST_TEST_universal": check j-i == 2 failed [2-1!=2]
674: error: in "test_BOOST_TEST_universal": check *p == 2 failed [1!=2]
677: error: in "test_BOOST_TEST_universal": check j-*p == 0 failed [2-1!=0]
680: info: check ( i > 5, true ) passed
684: error: in "test_BOOST_TEST_universal": check FooType() failed [(bool)0 is false]
685: error: in "test_BOOST_TEST_universal": check *F failed [(bool)0 is false]
686: error: in "test_BOOST_TEST_universal": check **F failed [(bool)0 is false]
687: error: in "test_BOOST_TEST_universal": check ***F failed [(bool)0 is false]
688: error: in "test_BOOST_TEST_universal": check &F > 100 failed [10<=100]
689: error: in "test_BOOST_TEST_universal": check &*F > 100 failed [10<=100]
692: error: in "test_BOOST_TEST_universal": check (i == 1) & (j == 1) failed [1&0]
693: error: in "test_BOOST_TEST_universal": check (i == 2) | (j == 1) failed [0|0]
696: error: in "test_BOOST_TEST_universal": check ( i == 1 && j == 1 ) failed
697: error: in "test_BOOST_TEST_universal": check ( i == 2 || j == 1 ) failed
700: error: in "test_BOOST_TEST_universal": This message reported instead
705: info: check true passed
711: info: check true passed
