139: warning: in "test_BOOST_WARN": condition sizeof(int) == sizeof(short) is not satisfied
142: info: check sizeof(unsigned char) == sizeof(char) passed
164: error: in "test_BOOST_CHECK": check false failed
165: error: in "test_BOOST_CHECK": check 1==2 failed
166: error: in "test_BOOST_CHECK": check i==1 failed
169: info: check i==2 passed
176: error: in "test_BOOST_REQUIRE": not aborted
178: fatal error: in "test_BOOST_REQUIRE": critical check false failed
182: fatal error: in "test_BOOST_REQUIRE": critical check j > 5 failed
185: info: check j < 5 passed
185: error: in "test_BOOST_REQUIRE": not aborted
199: info: check 'object size 33 is too small' passed
216: error: in "test_BOOST_CHECK_MESSAGE": Well, may be that what I believe in
218: error: in "test_BOOST_CHECK_MESSAGE": Checking predicate failed. Some explanation
221: info: check 'Could it fail?' passed
226: error: in "test_BOOST_CHECK_MESSAGE": Comparing 1 and 2: some explanation
233: fatal error: in "test_BOOST_REQUIRE_MESSAGE": Here we should stop
236: info: check 'That's OK' passed
236: error: in "test_BOOST_REQUIRE_MESSAGE": not aborted
243: error: in "test_BOOST_ERROR": Fail to miss an error
250: fatal error: in "test_BOOST_FAIL": No! No! Show must go on.
266: error: in "test_BOOST_CHECK_THROW": exception my_exception is expected
269: warning: in "test_BOOST_CHECK_THROW": exception my_exception is expected
272: fatal error: in "test_BOOST_CHECK_THROW": exception my_exception is expected
278: info: check 'exception my_exception is caught' passed
285: error: in "test_BOOST_CHECK_EXCEPTION": incorrect exception my_exception is caught
288: info: check 'incorrect exception my_exception is caught' passed
300: error: in "test_BOOST_CHECK_NO_THROW": exception thrown by throw my_exception()
346: error: in "test_BOOST_CHECK_EQUAL": check i == j failed [1 != 2]
352: error: in "test_BOOST_CHECK_EQUAL": check str1 == str2 failed [test1 != test12]
355: error: in "test_BOOST_CHECK_EQUAL": check i+1 == j failed [4 != 2]
358: info: check str1 == str3+1 passed
367: fatal error: in "test_BOOST_CHECK_EQUAL": critical check str1 == str2 failed [test != null string]
373: warning: in "test_BOOST_CHECK_EQUAL": condition b1 == b2 is not satisfied [B(1) != B(2)]
379: error: in "test_BOOST_CHECK_EQUAL": check c1 == c3 failed [C(0,100) != C(1,102)]. Index mismatch
380: error: in "test_BOOST_CHECK_EQUAL": check c1 == c2 failed [C(0,100) != C(0,101)]. Id mismatch
384: error: in "test_BOOST_CHECK_EQUAL": check ch1 == ch2 failed [0xfffffffe != 0xfffffffd]
395: error: in "test_BOOST_CHECK_LOGICAL_EXPR": check ++i != j failed [2 == 2]
397: error: in "test_BOOST_CHECK_LOGICAL_EXPR": check i < j failed [2 >= 2]
398: error: in "test_BOOST_CHECK_LOGICAL_EXPR": check i > j failed [2 <= 2]
405: error: in "test_BOOST_CHECK_LOGICAL_EXPR": check i <= j failed [3 > 2]
406: error: in "test_BOOST_CHECK_LOGICAL_EXPR": check j >= i failed [2 < 3]
411: error: in "test_BOOST_CHECK_LOGICAL_EXPR": check str1 != str2 failed [test1 == test1]
441: error: in "test_BOOST_CHECK_PREDICATE": check is_even( i ) failed for ( 17 )
444: error: in "test_BOOST_CHECK_PREDICATE": check not_equal_to<int>()( i, 17 ) failed for ( 17, 17 )
450: warning: in "test_BOOST_CHECK_PREDICATE": condition moo( 12, i, j ) is not satisfied for ( 12, 17, 15 )
458: error: in "test_BOOST_CHECK_PREDICATE": check compare_lists( l1, l2 ) failed for ( ,  ). Different sizes [2!=0]
469: error: in "test_BOOST_REQUIRE_PREDICATE": not aborted
471: fatal error: in "test_BOOST_REQUIRE_PREDICATE": critical check less_equal<int>()( arg2, arg1 ) failed for ( 2, 1 )
492: error: in "test_BOOST_CHECK_EQUAL_COLLECTIONS": check { testlist.begin(), testlist.end() } == { pattern, pattern+7 } failed. 
Mismatch in a position 2: 4 != 3
Mismatch in a position 5: 7 != 6
493: error: in "test_BOOST_CHECK_EQUAL_COLLECTIONS": check { testlist.begin(), testlist.end() } == { pattern, pattern+2 } failed. 
Collections size mismatch: 7 != 2
502: error: in "test_BOOST_CHECK_BITWISE_EQUAL": check (char)0x06 =.= (char)0x16 failed. 
Mismatch in a position 4
505: warning: in "test_BOOST_CHECK_BITWISE_EQUAL": condition (char)0x26 =.= (char)0x04 is not satisfied. 
Mismatch in a position 1
Mismatch in a position 5
508: fatal error: in "test_BOOST_CHECK_BITWISE_EQUAL": critical check (char)0x26 =.= (int)0x26 failed. 
Operands bit sizes mismatch: 8 != 32
still testing
1+1=2
2+2=4
struct A
0x14
  20
0: fatal error in "test_BOOST_TEST_CHECKPOINT": C string: some error
543: last checkpoint: Going to do a silly things
0: fatal error in "test_BOOST_TEST_PASSPOINT": unknown type
554: last checkpoint
611: error: in "test_context_logging": check false failed
Failure occurred in a following context:
    some context
615: error: in "test_context_logging": check false failed
Failure occurred in a following context:
    some more context: 12
620: error: in "test_context_logging": check false failed
Failure occurred in a following context:
    info 1
    info 2
    info 3
623: error: in "test_context_logging": check false failed
Failure occurred in a following context:
    some sticky context
626: error: in "test_context_logging": check false failed
Failure occurred in a following context:
    some sticky context
    more context
629: error: in "test_context_logging": check false failed
Failure occurred in a following context:
    some sticky context
    different subcontext
633: error: in "test_context_logging": check false failed
Failure occurred in a following context:
    outer context
636: error: in "test_context_logging": check false failed
Failure occurred in a following context:
    outer context
    inner context
639: error: in "test_context_logging": check false failed
Failure occurred in a following context:
    outer context
670: info: check true passed
671: error: in "test_BOOST_TEST_universal": check false failed
674: info: check bc passed
677: error: in "test_BOOST_TEST_universal": check i == 2 failed [1 != 2]
678: error: in "test_BOOST_TEST_universal": check i != 1 failed [1 == 1]
679: error: in "test_BOOST_TEST_universal": check i > 2 failed [1 <= 2]
680: error: in "test_BOOST_TEST_universal": check i < 1 failed [1 >= 1]
681: error: in "test_BOOST_TEST_universal": check i <= 0 failed [1 > 0]
682: error: in "test_BOOST_TEST_universal": check i >= 5 failed [1 < 5]
685: error: in "test_BOOST_TEST_universal": check i+j >= 5 failed [1 + 2 < 5]
686: error: in "test_BOOST_TEST_universal": check j-i == 2 failed [2 - 1 != 2]
689: error: in "test_BOOST_TEST_universal": check *p == 2 failed [1 != 2]
691: error: in "test_BOOST_TEST_universal": check j-*p == 0 failed [2 - 1 != 0]
693: info: check ( i > 5, true ) passed
697: error: in "test_BOOST_TEST_universal": check FooType() failed [(bool)0 is false]
698: error: in "test_BOOST_TEST_universal": check *F failed [(bool)0 is false]
699: error: in "test_BOOST_TEST_universal": check **F failed [(bool)0 is false]
700: error: in "test_BOOST_TEST_universal": check ***F failed [(bool)0 is false]
701: error: in "test_BOOST_TEST_universal": check &F > 100 failed [10 <= 100]
702: error: in "test_BOOST_TEST_universal": check &*F > 100 failed [10 <= 100]
704: error: in "test_BOOST_TEST_universal": check (i == 1) & (j == 1) failed [1 & 0]
705: error: in "test_BOOST_TEST_universal": check (i == 2) | (j == 1) failed [0 | 0]
707: error: in "test_BOOST_TEST_universal": check ( i == 1 && j == 1 ) failed
708: error: in "test_BOOST_TEST_universal": check ( i == 2 || j == 1 ) failed
710: error: in "test_BOOST_TEST_universal": This message reported instead
714: info: check true passed
720: info: check true passed
732: error: in "test_BOOST_TEST_universal": check v <= l failed.
Mismatch in a position 2: 3 > 2
733: error: in "test_BOOST_TEST_universal": check v == l failed.
Mismatch in a position 1: 2 != 3
Mismatch in a position 2: 3 != 2
